[package]
name = "bisq-cli"
version = "0.1.0"
authors = ["bodymindarts <bodymindarts@online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
